/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.MascotaControlador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.MascotasModelo;

/**
 *
 * @author USER-LENOVO
 */
public class MascotasVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form CitasVista
     */
    
    MascotaControlador mc = new MascotaControlador();
    ArrayList<MascotasModelo> listaMascotas;
    DefaultTableModel modelMascotas;
    
    public MascotasVista() {
        initComponents();
        modelMascotas = (DefaultTableModel) tblMascotas.getModel();
        listaMascotas = mc.listarMascotas();
        System.out.println("Número de citas recuperadas: " + listaMascotas.size());
        
        Object[] datosFila=new Object[modelMascotas.getColumnCount()];
        
        for (MascotasModelo mascota : listaMascotas) {
            datosFila[0] = mascota.getNombre();
            datosFila[1] = mascota.getCliente().getCedula();
            datosFila[2] = mascota.getTipoAnimal();
            datosFila[3] = mascota.getFechaNacimiento().toString();
            datosFila[4] = mascota.getPeso();
            datosFila[5] = mascota.getRaza();
            datosFila[6] = mascota.isVacunas();
            datosFila[7] = mascota.getObservaciones();
            datosFila[8] = "Editar";
            datosFila[9] = "Eliminar";
            modelMascotas.addRow(datosFila);
        }
        
        tblMascotas.setModel(modelMascotas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMascotas = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mascotas");

        tblMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mascota", "Dueño", "Tipo", "Fecha Nacimiento", "Peso", "Raza", "Vacunas", "Observaciones", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMascotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMascotas;
    // End of variables declaration//GEN-END:variables
}
